# Generated by Django 3.2.7 on 2021-09-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('resumen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('fechaNac', models.DateField()),
                ('sexo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pregunta_beck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.preguntabeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.user')),
            ],
        ),
    ]
