# Generated by Django 3.2.7 on 2021-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fechaNac',
            new_name='fecha_nacimiento',
        ),
    ]
